import React, { useState, useEffect, useRef } from 'react';
import { 
  Sparkles, 
  LayoutDashboard, 
  MessageSquare, 
  LogOut, 
  Plus, 
  Palette, 
  Type, 
  FileText, 
  Share2, 
  Download,
  Mic,
  MicOff,
  Image as ImageIcon,
  Trash2,
  Loader2,
  RefreshCw,
  X,
  MessageCircle,
  Search,
  MoreVertical,
  Edit2,
  Check,
  Upload,
  AlignLeft,
  AlignCenter,
  AlignRight,
  Globe,
  Link
} from 'lucide-react';
import { jsPDF } from "jspdf";
import { User, BrandProject, BrandGeneratedData, ChatMessage } from './types';
import { generateBrandIdentity, generateLogoIcon, getChatResponse } from './services/geminiService';
import { Button, Input, TextArea, Card, Select, ColorInput } from './components/UI';

// --- Constants & Helpers ---

const LANGUAGES = [
  { value: 'English', label: 'English' },
  { value: 'Hindi', label: 'Hindi' },
  { value: 'Telugu', label: 'Telugu' },
  { value: 'Tamil', label: 'Tamil' },
  { value: 'Spanish', label: 'Spanish' },
  { value: 'French', label: 'French' },
  { value: 'German', label: 'German' },
];

const FONT_OPTIONS = [
    { value: 'Montserrat', label: 'Modern Sans (Montserrat)' },
    { value: 'Playfair Display', label: 'Luxury Serif (Playfair)' },
    { value: 'Roboto Slab', label: 'Bold Slab (Roboto)' },
    { value: 'Lato', label: 'Friendly (Lato)' },
    { value: 'Pacifico', label: 'Handwritten (Pacifico)' },
    { value: 'Oswald', label: 'Strong (Oswald)' },
];

const simpleHash = (str: string) => {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i);
    hash = (hash << 5) - hash + char;
    hash = hash & hash;
  }
  return hash.toString();
};

const exportToPDF = (project: BrandProject) => {
  const doc = new jsPDF();
  const d = project.generatedData;
  if (!d) return;

  const margin = 20;
  let y = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  const contentWidth = pageWidth - (margin * 2);

  const addText = (text: string, size: number, style: 'normal' | 'bold' = 'normal', color: [number, number, number] = [40, 40, 40]) => {
    doc.setFontSize(size);
    doc.setFont("helvetica", style);
    doc.setTextColor(color[0], color[1], color[2]);
    const lines = doc.splitTextToSize(text, contentWidth);
    
    if (y + (lines.length * size * 0.4) > 280) {
        doc.addPage();
        y = 20;
    }
    
    doc.text(lines, margin, y);
    y += (lines.length * size * 0.4) + 6;
  };

  const addSectionTitle = (title: string) => {
      y += 10;
      addText(title, 18, 'bold', [79, 70, 229]); // Indigo color
      y += 2;
  };

  // Title Page
  doc.setFontSize(40);
  doc.setTextColor(79, 70, 229);
  doc.text(project.name || "Brand Identity", pageWidth / 2, 100, { align: 'center' });
  doc.setFontSize(14);
  doc.setTextColor(100, 100, 100);
  doc.text("Generated by BrandForge AI", pageWidth / 2, 115, { align: 'center' });
  doc.text(new Date().toLocaleDateString(), pageWidth / 2, 125, { align: 'center' });
  doc.addPage();
  y = 20;

  // Overview
  addSectionTitle("Brand Overview");
  addText(`Industry: ${project.industry}`, 12);
  addText(`Tone: ${project.tone}`, 12);
  addText(`Taglines:`, 14, 'bold');
  d.taglines.forEach(t => addText(`• ${t}`, 11));
  
  // Strategy
  addSectionTitle("Strategic Core");
  addText("Vision", 14, 'bold');
  addText(d.story.vision, 11);
  addText("Mission", 14, 'bold');
  addText(d.story.mission, 11);
  addText("Positioning", 14, 'bold');
  addText(d.story.positioning, 11);
  addText("Problem & Solution", 14, 'bold');
  addText(`Problem: ${d.story.problem}`, 11);
  addText(`Solution: ${d.story.solution}`, 11);

  // Visuals
  doc.addPage();
  y = 20;
  addSectionTitle("Visual Identity");
  
  // Colors
  addText("Primary Colors", 14, 'bold');
  const palette = d.visuals.palettes[d.visuals.selectedPaletteIndex || 0];
  let xOffset = margin;
  palette.colors.forEach((c) => {
      doc.setFillColor(c);
      doc.rect(xOffset, y, 30, 30, 'F');
      doc.setFontSize(10);
      doc.setTextColor(60, 60, 60);
      doc.text(c, xOffset, y + 36);
      xOffset += 35;
  });
  y += 50;

  // Typography
  addText("Typography", 14, 'bold');
  addText(`Logo Font: ${d.visuals.fonts.logo}`, 11);
  addText(`Heading Font: ${d.visuals.fonts.heading}`, 11);
  addText(`Body Font: ${d.visuals.fonts.body}`, 11);

  // Logo
  if (d.visuals.logoIconUrl) {
      addText("Logo Concept", 14, 'bold');
      try {
          doc.addImage(d.visuals.logoIconUrl, 'PNG', margin, y, 50, 50);
          addText(`Prompt: ${d.visuals.logoPrompt}`, 10);
          y += 60;
      } catch (e) {
          console.error("Could not add image to PDF", e);
      }
  }

  // Marketing
  doc.addPage();
  y = 20;
  addSectionTitle("Marketing Assets");
  addText("Descriptions", 14, 'bold');
  addText(d.marketing.shortDescription, 11);
  y += 5;
  addText(d.marketing.longDescription, 11);
  
  addText("Sample Email Copy", 14, 'bold');
  addText(d.marketing.emailCopy, 10);

  addText("Social Media Captions", 14, 'bold');
  d.marketing.socialCaptions.forEach(c => addText(`- ${c}`, 10));

  doc.save(`${project.name.replace(/\s+/g, '_')}_BrandKit.pdf`);
};

// --- Components ---

const AuthScreen: React.FC<{ onLogin: (u: User) => void }> = ({ onLogin }) => {
  const [isLogin, setIsLogin] = useState(true);
  const [email, setEmail] = useState('');
  const [name, setName] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [error, setError] = useState('');

  const handleAuth = (e: React.FormEvent) => {
    e.preventDefault();
    setError('');

    if (!isLogin && password !== confirmPassword) {
        setError("Passwords do not match.");
        return;
    }

    const users: User[] = JSON.parse(localStorage.getItem('bf_users') || '[]');
    const hashedPassword = simpleHash(password);

    if (isLogin) {
      const user = users.find(u => u.email === email && u.passwordHash === hashedPassword);
      if (user) {
        localStorage.setItem('bf_session', JSON.stringify(user));
        onLogin(user);
      } else {
        setError('Invalid credentials or account does not exist.');
      }
    } else {
      if (users.find(u => u.email === email)) {
        setError('User already exists. Please login.');
        return;
      }
      const newUser: User = {
        id: Date.now().toString(),
        email,
        name: name || email.split('@')[0],
        passwordHash: hashedPassword
      };
      users.push(newUser);
      localStorage.setItem('bf_users', JSON.stringify(users));
      localStorage.setItem('bf_session', JSON.stringify(newUser));
      onLogin(newUser);
    }
  };

  const mockSocialLogin = (provider: string) => {
      alert(`${provider} login is mocked for this demo. Logging you in as a test user.`);
      const mockUser: User = {
          id: `social-${Date.now()}`,
          email: `user@${provider.toLowerCase()}.com`,
          name: `Test User (${provider})`,
          passwordHash: 'social-mock-hash'
      };
      localStorage.setItem('bf_session', JSON.stringify(mockUser));
      onLogin(mockUser);
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-indigo-50 to-purple-50 p-4">
      <Card className="w-full max-w-md bg-white/80 backdrop-blur-xl border-white/50 shadow-2xl">
        <div className="text-center mb-8">
          <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-gradient-to-tr from-indigo-500 to-purple-500 mb-4 shadow-lg shadow-indigo-200 animate-pulse">
            <Sparkles className="w-8 h-8 text-white" />
          </div>
          <h1 className="text-3xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-slate-700 to-slate-900">
            BrandForge AI
          </h1>
          <p className="text-slate-500 mt-2">Craft your identity with generative intelligence.</p>
        </div>

        <form onSubmit={handleAuth} className="space-y-4">
          {!isLogin && (
            <Input 
              label="Full Name" 
              placeholder="John Doe" 
              value={name} 
              onChange={e => setName(e.target.value)} 
              required={!isLogin}
            />
          )}
          <Input 
            label="Email Address" 
            type="email" 
            placeholder="john@example.com" 
            value={email} 
            onChange={e => setEmail(e.target.value)}
            required 
          />
          <Input 
            label="Password" 
            type="password" 
            placeholder="••••••••" 
            value={password}
            onChange={e => setPassword(e.target.value)}
            required 
          />
          {!isLogin && (
              <Input 
                label="Confirm Password" 
                type="password" 
                placeholder="••••••••" 
                value={confirmPassword}
                onChange={e => setConfirmPassword(e.target.value)}
                required 
              />
          )}
          
          {error && <p className="text-red-500 text-sm text-center">{error}</p>}

          <Button type="submit" className="w-full py-3 text-lg">
            {isLogin ? 'Sign In' : 'Create Account'}
          </Button>
        </form>

        <div className="relative my-6">
            <div className="absolute inset-0 flex items-center">
                <span className="w-full border-t border-slate-200"></span>
            </div>
            <div className="relative flex justify-center text-xs uppercase">
                <span className="bg-white px-2 text-slate-500">Or continue with</span>
            </div>
        </div>

        <div className="grid grid-cols-2 gap-4">
            <Button variant="secondary" type="button" onClick={() => mockSocialLogin('Google')}>
                <span className="mr-2">G</span> Google
            </Button>
            <Button variant="secondary" type="button" onClick={() => mockSocialLogin('LinkedIn')}>
                <span className="mr-2 font-bold text-blue-700">in</span> LinkedIn
            </Button>
        </div>

        <div className="mt-6 text-center text-sm text-slate-500">
          {isLogin ? "Don't have an account? " : "Already have an account? "}
          <button 
            onClick={() => { setIsLogin(!isLogin); setError(''); }} 
            className="text-indigo-600 font-medium hover:underline"
          >
            {isLogin ? 'Sign up' : 'Log in'}
          </button>
        </div>
      </Card>
    </div>
  );
};

const ChatWidget: React.FC = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const chatEndRef = useRef<HTMLDivElement>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  // Load chat session from sessionStorage
  useEffect(() => {
      const saved = sessionStorage.getItem('bf_chat_session');
      if (saved) setMessages(JSON.parse(saved));
  }, []);

  // Save chat session
  useEffect(() => {
      if (messages.length > 0) {
        sessionStorage.setItem('bf_chat_session', JSON.stringify(messages));
      }
  }, [messages]);

  const sendMessage = async () => {
    if (!input.trim()) return;
    const userMsg: ChatMessage = { role: 'user', text: input, timestamp: Date.now() };
    setMessages(prev => [...prev, userMsg]);
    setInput('');
    setIsLoading(true);

    // Reset height
    if (textareaRef.current) textareaRef.current.style.height = 'auto';

    try {
        const history = messages.map(m => ({
            role: m.role === 'user' ? 'user' : 'model',
            parts: [{ text: m.text }]
        }));
        const response = await getChatResponse(history, userMsg.text);
        setMessages(prev => [...prev, { role: 'model', text: response || "I'm here to help.", timestamp: Date.now() }]);
    } catch (e) {
        setMessages(prev => [...prev, { role: 'model', text: "Sorry, I can't connect right now.", timestamp: Date.now() }]);
    } finally {
        setIsLoading(false);
        setTimeout(() => chatEndRef.current?.scrollIntoView({ behavior: 'smooth' }), 100);
    }
  };

  const handleInput = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
      setInput(e.target.value);
      e.target.style.height = 'auto';
      e.target.style.height = `${e.target.scrollHeight}px`;
  };

  return (
    <div className="fixed bottom-6 right-6 z-50">
      {!isOpen && (
        <button 
          onClick={() => setIsOpen(true)}
          className="w-16 h-16 bg-gradient-to-r from-indigo-600 to-purple-600 rounded-full shadow-2xl flex items-center justify-center text-white hover:scale-105 transition-transform"
        >
          <MessageCircle className="w-8 h-8" />
        </button>
      )}
      
      {isOpen && (
        <div className="w-[350px] h-[500px] bg-white rounded-2xl shadow-2xl border border-slate-200 flex flex-col overflow-hidden animate-in slide-in-from-bottom-5">
          <div className="p-4 bg-slate-900 text-white flex justify-between items-center">
            <div className="flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-yellow-400" />
                <span className="font-bold">Granite Consultant</span>
            </div>
            <button onClick={() => setIsOpen(false)} className="text-white/70 hover:text-white"><X className="w-5 h-5"/></button>
          </div>
          
          <div className="flex-1 overflow-y-auto p-4 space-y-4 bg-slate-50">
             {messages.length === 0 && (
                 <div className="text-center text-slate-400 text-sm mt-10">
                     <p>Tell me about your business idea.</p>
                     <p>I'll help you refine it for better branding.</p>
                 </div>
             )}
             {messages.map((m, i) => (
                 <div key={i} className={`flex ${m.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                     <div className={`max-w-[85%] p-3 rounded-xl text-sm ${m.role === 'user' ? 'bg-indigo-600 text-white rounded-tr-none' : 'bg-white border border-slate-200 text-slate-700 rounded-tl-none'}`}>
                         {m.text}
                     </div>
                 </div>
             ))}
             {isLoading && <Loader2 className="w-5 h-5 text-slate-400 animate-spin" />}
             <div ref={chatEndRef} />
          </div>

          <div className="p-3 border-t bg-white">
              <div className="flex items-end gap-2">
                  <textarea 
                    ref={textareaRef}
                    className="flex-1 text-sm bg-slate-100 rounded-lg px-3 py-2 outline-none resize-none max-h-32"
                    placeholder="Ask for advice..."
                    value={input}
                    rows={1}
                    onChange={handleInput}
                    onKeyDown={e => {
                        if (e.key === 'Enter' && !e.shiftKey) {
                            e.preventDefault();
                            sendMessage();
                        }
                    }}
                  />
                  <button onClick={sendMessage} disabled={isLoading} className="p-2 mb-0.5 bg-indigo-600 text-white rounded-lg">
                      <MessageSquare className="w-4 h-4" />
                  </button>
              </div>
          </div>
        </div>
      )}
    </div>
  );
};

const ProjectEditor: React.FC<{
  project: BrandProject,
  onUpdate: (p: BrandProject) => void,
  onBack: () => void
}> = ({ project, onUpdate, onBack }) => {
  const [activeTab, setActiveTab] = useState<'overview' | 'story' | 'visuals' | 'marketing'>('overview');
  const [data, setData] = useState<BrandGeneratedData | undefined>(project.generatedData);
  const [isGeneratingLogo, setIsGeneratingLogo] = useState(false);

  // Sync data
  useEffect(() => {
    if (data && JSON.stringify(data) !== JSON.stringify(project.generatedData)) {
      onUpdate({ ...project, generatedData: data });
    }
  }, [data]);

  const handleGenerateLogo = async () => {
    if (!data?.visuals.logoPrompt) return;
    setIsGeneratingLogo(true);
    try {
      const url = await generateLogoIcon(data.visuals.logoPrompt, data.sentiment.mood);
      setData(prev => prev ? ({
        ...prev,
        visuals: { ...prev.visuals, logoIconUrl: url }
      }) : undefined);
    } catch (e) {
      alert("Failed to generate logo. Please try again.");
    } finally {
      setIsGeneratingLogo(false);
    }
  };

  if (!data) return <div>Loading data...</div>;

  const currentPalette = data.visuals.palettes[data.visuals.selectedPaletteIndex || 0];
  const logoSettings = data.visuals.logoSettings || {
      fontFamily: data.visuals.fonts.logo,
      layout: 'vertical',
      spacing: 2,
      fontSize: 40,
      textColor: currentPalette.colors[0],
      bgColor: '#ffffff',
      iconColor: currentPalette.colors[0],
      iconSize: 150,
      borderRadius: 16,
      textAlignment: 'center',
      tintIcon: false
  };

  return (
    <div className="flex h-screen overflow-hidden bg-slate-50">
      {/* Sidebar */}
      <div className="w-64 bg-white border-r border-slate-200 flex flex-col">
        <div className="p-6 border-b border-slate-100">
          <button onClick={onBack} className="flex items-center text-sm text-slate-500 hover:text-indigo-600 mb-4 transition-colors">
            ← Back to Dashboard
          </button>
          <h1 className="font-bold text-xl text-slate-800 break-words">{project.name}</h1>
          <p className="text-xs text-slate-400 mt-1">{project.industry}</p>
        </div>
        
        <nav className="flex-1 p-4 space-y-2 overflow-y-auto">
          {[
            { id: 'overview', icon: LayoutDashboard, label: 'Overview' },
            { id: 'story', icon: FileText, label: 'Brand Story' },
            { id: 'visuals', icon: Palette, label: 'Visual Identity' },
            { id: 'marketing', icon: Share2, label: 'Marketing' },
          ].map(item => (
            <button
              key={item.id}
              onClick={() => setActiveTab(item.id as any)}
              className={`w-full flex items-center px-4 py-3 rounded-xl text-sm font-medium transition-all ${
                activeTab === item.id 
                  ? 'bg-indigo-50 text-indigo-700 shadow-sm' 
                  : 'text-slate-600 hover:bg-slate-50'
              }`}
            >
              <item.icon className={`w-4 h-4 mr-3 ${activeTab === item.id ? 'text-indigo-600' : 'text-slate-400'}`} />
              {item.label}
            </button>
          ))}
        </nav>

        <div className="p-4 border-t border-slate-100 space-y-2">
            <Button variant="secondary" className="w-full justify-start text-sm" onClick={() => exportToPDF(project)}>
                <Download className="w-4 h-4 mr-2" /> PDF Brand Kit
            </Button>
        </div>
      </div>

      {/* Main Content */}
      <div className="flex-1 overflow-y-auto p-8">
        
        {/* Overview Tab */}
        {activeTab === 'overview' && (
          <div className="max-w-4xl mx-auto space-y-8">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <Card title="Brand Names" className="md:col-span-2">
                    <ul className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        {data.names.map((nObj, i) => (
                            <li key={i} className="flex flex-col p-4 bg-white border border-slate-100 rounded-xl group hover:shadow-md transition-all relative">
                                <div className="flex justify-between items-start">
                                    <span className={`text-xl font-bold ${nObj.name === project.name ? "text-indigo-600" : "text-slate-800"}`} style={{ fontFamily: logoSettings.fontFamily }}>{nObj.name}</span>
                                    {nObj.name !== project.name && (
                                        <button 
                                            onClick={() => onUpdate({...project, name: nObj.name})}
                                            className="text-xs font-medium text-indigo-500 opacity-0 group-hover:opacity-100 hover:underline bg-indigo-50 px-2 py-1 rounded"
                                        >
                                            Select
                                        </button>
                                    )}
                                </div>
                                <p className="text-sm text-slate-500 mt-2 italic">"{nObj.meaning}"</p>
                            </li>
                        ))}
                    </ul>
                </Card>
                <Card title="Strategic Analysis">
                    <div className="space-y-4">
                        <div className="p-4 bg-indigo-50 rounded-xl border border-indigo-100">
                             <div className="text-xs text-indigo-400 uppercase font-bold mb-1">Detected Mood</div>
                             <div className="text-lg font-semibold text-indigo-900 capitalize">{data.sentiment.mood}</div>
                        </div>
                        <div className="flex justify-between items-center">
                            <span className="text-sm text-slate-500">Tone Alignment</span>
                            <span className="text-sm font-medium text-slate-800">{data.sentiment.toneAlignment}</span>
                        </div>
                        <div>
                            <div className="flex justify-between text-sm mb-1">
                                <span className="text-slate-500">Confidence</span>
                                <span className="font-medium text-indigo-600">{(data.sentiment.confidence * 100).toFixed(0)}%</span>
                            </div>
                            <div className="w-full bg-slate-100 rounded-full h-2">
                                <div className="bg-indigo-500 h-2 rounded-full" style={{ width: `${data.sentiment.confidence * 100}%` }}></div>
                            </div>
                        </div>
                    </div>
                </Card>
                <Card title="Taglines">
                    <div className="grid grid-cols-1 gap-3">
                        {data.taglines.map((t, i) => (
                            <div key={i} className="p-4 bg-white rounded-xl text-slate-700 border border-slate-200 shadow-sm italic text-lg text-center">
                                "{t}"
                            </div>
                        ))}
                    </div>
                </Card>
            </div>
          </div>
        )}

        {/* Story Tab */}
        {activeTab === 'story' && (
            <div className="max-w-4xl mx-auto space-y-6">
                <Card title="Vision & Mission">
                    <div className="space-y-4">
                        <div>
                            <label className="text-xs font-bold text-indigo-500 uppercase tracking-wider">Vision</label>
                            <TextArea 
                                value={data.story.vision} 
                                onChange={e => setData({...data, story: {...data.story, vision: e.target.value}})}
                                className="mt-1 min-h-[80px]"
                            />
                        </div>
                        <div>
                            <label className="text-xs font-bold text-indigo-500 uppercase tracking-wider">Mission</label>
                            <TextArea 
                                value={data.story.mission} 
                                onChange={e => setData({...data, story: {...data.story, mission: e.target.value}})}
                                className="mt-1 min-h-[80px]"
                            />
                        </div>
                    </div>
                </Card>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <Card title="The Problem">
                        <TextArea 
                            value={data.story.problem} 
                            onChange={e => setData({...data, story: {...data.story, problem: e.target.value}})}
                            className="min-h-[150px] bg-red-50/50 border-red-100 focus:ring-red-200"
                        />
                    </Card>
                    <Card title="Our Solution">
                        <TextArea 
                            value={data.story.solution} 
                            onChange={e => setData({...data, story: {...data.story, solution: e.target.value}})}
                            className="min-h-[150px] bg-green-50/50 border-green-100 focus:ring-green-200"
                        />
                    </Card>
                </div>
                <Card title="Market Positioning">
                    <TextArea 
                        value={data.story.positioning} 
                        onChange={e => setData({...data, story: {...data.story, positioning: e.target.value}})}
                    />
                </Card>
            </div>
        )}

        {/* Visuals Tab */}
        {activeTab === 'visuals' && (
            <div className="max-w-5xl mx-auto space-y-8">
                {/* Palette Selector */}
                <Card title="Logo Composer" className="overflow-hidden">
                    <div className="flex flex-col lg:flex-row gap-8">
                        {/* Preview Area */}
                        <div className="flex-1 flex items-center justify-center bg-slate-100 rounded-xl border border-slate-200 min-h-[400px] p-8 relative pattern-grid">
                            <div 
                                style={{
                                    backgroundColor: logoSettings.bgColor,
                                    borderRadius: `${logoSettings.borderRadius}px`,
                                    padding: '40px',
                                    display: 'flex',
                                    flexDirection: logoSettings.layout === 'vertical' ? 'column' : 'row',
                                    alignItems: 'center',
                                    justifyContent: 'center',
                                    gap: '20px',
                                    boxShadow: '0 10px 30px -10px rgba(0,0,0,0.1)',
                                    transition: 'all 0.3s ease'
                                }}
                            >
                                {data.visuals.logoIconUrl ? (
                                    <div style={{
                                        width: `${logoSettings.iconSize}px`,
                                        height: `${logoSettings.iconSize}px`,
                                        position: 'relative'
                                    }}>
                                        <img 
                                            src={data.visuals.logoIconUrl} 
                                            alt="Logo Icon" 
                                            className="w-full h-full object-contain"
                                            style={{
                                                filter: logoSettings.tintIcon ? 'grayscale(100%) brightness(0)' : 'none',
                                                // If masking is needed for color change of png:
                                                // maskImage: `url(${data.visuals.logoIconUrl})`,
                                                // WebkitMaskImage: `url(${data.visuals.logoIconUrl})`,
                                                // maskSize: 'contain',
                                                // WebkitMaskSize: 'contain',
                                                // maskRepeat: 'no-repeat',
                                                // backgroundColor: logoSettings.tintIcon ? logoSettings.iconColor : 'transparent'
                                            }}
                                        />
                                        {/* Fallback Tint Overlay for simple coloring if filter doesn't suffice */}
                                        {logoSettings.tintIcon && (
                                            <div 
                                                className="absolute inset-0 w-full h-full"
                                                style={{
                                                    backgroundColor: logoSettings.iconColor,
                                                    maskImage: `url(${data.visuals.logoIconUrl})`,
                                                    WebkitMaskImage: `url(${data.visuals.logoIconUrl})`,
                                                    maskSize: 'contain',
                                                    WebkitMaskSize: 'contain',
                                                    maskRepeat: 'no-repeat',
                                                    maskPosition: 'center',
                                                    WebkitMaskPosition: 'center',
                                                }}
                                            />
                                        )}
                                    </div>
                                ) : (
                                    <div className="w-32 h-32 bg-slate-100 rounded-full flex items-center justify-center text-slate-300">
                                        <ImageIcon className="w-10 h-10" />
                                    </div>
                                )}
                                
                                <div style={{ 
                                    fontFamily: logoSettings.fontFamily, 
                                    color: logoSettings.textColor,
                                    fontSize: `${logoSettings.fontSize}px`,
                                    letterSpacing: `${logoSettings.spacing}px`,
                                    textAlign: logoSettings.textAlignment as any
                                }} className="font-bold leading-tight transition-all">
                                    {project.name}
                                </div>
                            </div>
                        </div>

                        {/* Controls */}
                        <div className="w-full lg:w-80 space-y-6 max-h-[600px] overflow-y-auto pr-2">
                            {/* Layout Controls */}
                            <div className="space-y-4 p-4 bg-slate-50 rounded-xl border border-slate-100">
                                <h4 className="font-medium text-slate-700 flex items-center gap-2"><ImageIcon className="w-4 h-4"/> Layout & Shape</h4>
                                <div className="flex gap-2">
                                    <Button 
                                        variant="secondary" 
                                        className={`flex-1 text-xs ${logoSettings.layout === 'vertical' ? 'bg-indigo-100 border-indigo-200' : ''}`}
                                        onClick={() => setData({ ...data, visuals: { ...data.visuals, logoSettings: {...logoSettings, layout: 'vertical'} } })}
                                    >
                                        Vertical
                                    </Button>
                                    <Button 
                                        variant="secondary" 
                                        className={`flex-1 text-xs ${logoSettings.layout === 'horizontal' ? 'bg-indigo-100 border-indigo-200' : ''}`}
                                        onClick={() => setData({ ...data, visuals: { ...data.visuals, logoSettings: {...logoSettings, layout: 'horizontal'} } })}
                                    >
                                        Horizontal
                                    </Button>
                                </div>
                                <div className="flex gap-2">
                                    <button onClick={() => setData({ ...data, visuals: { ...data.visuals, logoSettings: {...logoSettings, textAlignment: 'left'} } })} className={`p-2 rounded ${logoSettings.textAlignment === 'left' ? 'bg-indigo-100' : 'bg-white'}`}><AlignLeft className="w-4 h-4"/></button>
                                    <button onClick={() => setData({ ...data, visuals: { ...data.visuals, logoSettings: {...logoSettings, textAlignment: 'center'} } })} className={`p-2 rounded ${logoSettings.textAlignment === 'center' ? 'bg-indigo-100' : 'bg-white'}`}><AlignCenter className="w-4 h-4"/></button>
                                    <button onClick={() => setData({ ...data, visuals: { ...data.visuals, logoSettings: {...logoSettings, textAlignment: 'right'} } })} className={`p-2 rounded ${logoSettings.textAlignment === 'right' ? 'bg-indigo-100' : 'bg-white'}`}><AlignRight className="w-4 h-4"/></button>
                                </div>
                                <div>
                                    <label className="text-xs font-medium text-slate-500">Card Roundness</label>
                                    <input 
                                        type="range" min="0" max="100" 
                                        value={logoSettings.borderRadius}
                                        onChange={(e) => setData({ ...data, visuals: { ...data.visuals, logoSettings: {...logoSettings, borderRadius: Number(e.target.value)} } })}
                                        className="w-full"
                                    />
                                </div>
                                <div>
                                    <label className="text-xs font-medium text-slate-500">Icon Size</label>
                                    <input 
                                        type="range" min="50" max="300" 
                                        value={logoSettings.iconSize}
                                        onChange={(e) => setData({ ...data, visuals: { ...data.visuals, logoSettings: {...logoSettings, iconSize: Number(e.target.value)} } })}
                                        className="w-full"
                                    />
                                </div>
                            </div>

                            {/* Colors */}
                            <div className="space-y-4 p-4 bg-slate-50 rounded-xl border border-slate-100">
                                <h4 className="font-medium text-slate-700 flex items-center gap-2"><Palette className="w-4 h-4"/> Colors</h4>
                                <div className="grid grid-cols-2 gap-4">
                                    <ColorInput 
                                        label="Background"
                                        value={logoSettings.bgColor}
                                        onChange={(e) => setData({ ...data, visuals: { ...data.visuals, logoSettings: {...logoSettings, bgColor: e.target.value} } })}
                                    />
                                    <ColorInput 
                                        label="Text Color"
                                        value={logoSettings.textColor}
                                        onChange={(e) => setData({ ...data, visuals: { ...data.visuals, logoSettings: {...logoSettings, textColor: e.target.value} } })}
                                    />
                                </div>
                                <div>
                                    <div className="flex items-center justify-between mb-2">
                                        <span className="text-xs font-medium text-slate-500">Icon Tint</span>
                                        <input 
                                            type="checkbox" 
                                            checked={logoSettings.tintIcon} 
                                            onChange={(e) => setData({ ...data, visuals: { ...data.visuals, logoSettings: {...logoSettings, tintIcon: e.target.checked} } })}
                                        />
                                    </div>
                                    {logoSettings.tintIcon && (
                                        <ColorInput 
                                            label="Icon Color"
                                            value={logoSettings.iconColor}
                                            onChange={(e) => setData({ ...data, visuals: { ...data.visuals, logoSettings: {...logoSettings, iconColor: e.target.value} } })}
                                        />
                                    )}
                                </div>
                            </div>

                            {/* Typography */}
                            <div className="space-y-4 p-4 bg-slate-50 rounded-xl border border-slate-100">
                                <h4 className="font-medium text-slate-700 flex items-center gap-2"><Type className="w-4 h-4"/> Typography</h4>
                                <Select 
                                    label="Font Family"
                                    options={FONT_OPTIONS}
                                    value={logoSettings.fontFamily}
                                    onChange={(e) => setData({ ...data, visuals: { ...data.visuals, logoSettings: {...logoSettings, fontFamily: e.target.value} } })}
                                />
                                <div>
                                    <label className="text-xs font-medium text-slate-500">Font Size</label>
                                    <input 
                                        type="range" min="20" max="100" 
                                        value={logoSettings.fontSize}
                                        onChange={(e) => setData({ ...data, visuals: { ...data.visuals, logoSettings: {...logoSettings, fontSize: Number(e.target.value)} } })}
                                        className="w-full"
                                    />
                                </div>
                                <div>
                                    <label className="text-xs font-medium text-slate-500">Letter Spacing</label>
                                    <input 
                                        type="range" min="0" max="20" 
                                        value={logoSettings.spacing}
                                        onChange={(e) => setData({ ...data, visuals: { ...data.visuals, logoSettings: {...logoSettings, spacing: Number(e.target.value)} } })}
                                        className="w-full"
                                    />
                                </div>
                            </div>
                            
                            {/* Generation */}
                            <div className="space-y-4 p-4 bg-slate-50 rounded-xl border border-slate-100">
                                <h4 className="font-medium text-slate-700">Icon Generation</h4>
                                <TextArea 
                                    label="Icon Prompt Idea"
                                    value={data.visuals.logoPrompt}
                                    onChange={e => setData({...data, visuals: {...data.visuals, logoPrompt: e.target.value}})}
                                    className="text-xs"
                                />
                                <Button onClick={handleGenerateLogo} isLoading={isGeneratingLogo} className="w-full">
                                    <RefreshCw className="w-4 h-4 mr-2" />
                                    {data.visuals.logoIconUrl ? 'Regenerate Icon' : 'Generate Icon'}
                                </Button>
                            </div>
                        </div>
                    </div>
                </Card>
            </div>
        )}

        {/* Marketing Tab */}
        {activeTab === 'marketing' && (
            <div className="max-w-4xl mx-auto space-y-6">
                <Card title="Descriptions">
                    <div className="space-y-4">
                        <TextArea 
                            label="Short Description"
                            value={data.marketing.shortDescription} 
                            onChange={e => setData({...data, marketing: {...data.marketing, shortDescription: e.target.value}})}
                        />
                         <TextArea 
                            label="Long Description"
                            value={data.marketing.longDescription} 
                            onChange={e => setData({...data, marketing: {...data.marketing, longDescription: e.target.value}})}
                            className="min-h-[150px]"
                        />
                    </div>
                </Card>
                <Card title="Email Copy">
                     <TextArea 
                        value={data.marketing.emailCopy} 
                        onChange={e => setData({...data, marketing: {...data.marketing, emailCopy: e.target.value}})}
                        className="min-h-[300px] font-mono text-sm"
                    />
                </Card>
                <Card title="Social Media Captions">
                     <div className="space-y-3">
                         {data.marketing.socialCaptions.map((cap, i) => (
                             <div key={i} className="p-3 bg-white border border-slate-200 rounded-lg text-sm text-slate-600">
                                 {cap}
                             </div>
                         ))}
                     </div>
                </Card>
            </div>
        )}
      </div>
      <ChatWidget />
    </div>
  );
};

const Dashboard: React.FC<{
  user: User;
  projects: BrandProject[];
  onNew: () => void;
  onSelect: (p: BrandProject) => void;
  onDelete: (id: string) => void;
  onRename: (id: string, name: string) => void;
}> = ({ user, projects, onNew, onSelect, onDelete, onRename }) => {
  const [searchTerm, setSearchTerm] = useState('');
  const [sortBy, setSortBy] = useState<'date' | 'name'>('date');
  const [contextMenu, setContextMenu] = useState<string | null>(null);

  const filteredProjects = projects
    .filter(p => p.name.toLowerCase().includes(searchTerm.toLowerCase()) || p.industry.toLowerCase().includes(searchTerm.toLowerCase()))
    .sort((a, b) => {
        if (sortBy === 'date') return b.createdAt - a.createdAt;
        return a.name.localeCompare(b.name);
    });

  return (
    <div className="max-w-7xl mx-auto px-6 py-8" onClick={() => setContextMenu(null)}>
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8">
        <div>
          <h1 className="text-2xl font-bold text-slate-800">Welcome back, {user.name}</h1>
          <p className="text-slate-500">Manage your brand identities</p>
        </div>
        <div className="flex items-center gap-3">
            <div className="relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                <input 
                    className="pl-10 pr-4 py-2 bg-white border border-slate-200 rounded-xl text-sm focus:ring-2 focus:ring-indigo-500 outline-none w-64"
                    placeholder="Search projects..."
                    value={searchTerm}
                    onChange={e => setSearchTerm(e.target.value)}
                />
            </div>
            <select 
                className="px-4 py-2 bg-white border border-slate-200 rounded-xl text-sm outline-none"
                value={sortBy}
                onChange={e => setSortBy(e.target.value as any)}
            >
                <option value="date">Sort by Date</option>
                <option value="name">Sort by Name</option>
            </select>
            <Button onClick={onNew}>
                <Plus className="w-5 h-5 mr-2" />
                New Project
            </Button>
        </div>
      </div>

      {projects.length === 0 ? (
        <div className="text-center py-20 bg-white rounded-2xl border border-dashed border-slate-300">
          <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-slate-100 mb-4">
            <LayoutDashboard className="w-8 h-8 text-slate-400" />
          </div>
          <h3 className="text-lg font-medium text-slate-900">No projects yet</h3>
          <p className="text-slate-500 mb-6">Start building your first brand identity today.</p>
          <Button onClick={onNew} variant="primary">Create Brand</Button>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {filteredProjects.map(project => (
            <div key={project.id} className="bg-white p-6 rounded-2xl border border-slate-200 hover:shadow-lg transition-shadow group relative">
              <div className="absolute top-4 right-4 z-10">
                 <button 
                    onClick={(e) => { 
                        e.stopPropagation(); 
                        setContextMenu(contextMenu === project.id ? null : project.id); 
                    }} 
                    className="p-2 text-slate-400 hover:text-indigo-500 bg-white rounded-full shadow-sm border border-slate-100"
                 >
                    <MoreVertical className="w-4 h-4" />
                 </button>
                 {contextMenu === project.id && (
                     <div className="absolute right-0 mt-2 w-40 bg-white rounded-xl shadow-xl border border-slate-100 overflow-hidden z-20">
                         <button 
                             className="w-full text-left px-4 py-2 text-sm text-slate-600 hover:bg-slate-50 flex items-center gap-2"
                             onClick={(e) => {
                                 e.stopPropagation();
                                 const newName = prompt("Enter new name:", project.name);
                                 if (newName) onRename(project.id, newName);
                                 setContextMenu(null);
                             }}
                         >
                             <Edit2 className="w-4 h-4" /> Rename
                         </button>
                         <button 
                             className="w-full text-left px-4 py-2 text-sm text-slate-600 hover:bg-slate-50 flex items-center gap-2"
                             onClick={(e) => {
                                 e.stopPropagation();
                                 alert(`Share Link copied: https://brandforge.ai/p/${project.id}`);
                                 setContextMenu(null);
                             }}
                         >
                             <Share2 className="w-4 h-4" /> Share
                         </button>
                         <button 
                             className="w-full text-left px-4 py-2 text-sm text-red-600 hover:bg-red-50 flex items-center gap-2"
                             onClick={(e) => {
                                 e.stopPropagation();
                                 onDelete(project.id);
                             }}
                         >
                             <Trash2 className="w-4 h-4" /> Delete
                         </button>
                     </div>
                 )}
              </div>
              <div onClick={() => onSelect(project)} className="cursor-pointer h-full flex flex-col">
                <div className="flex items-center gap-3 mb-4">
                    <div className="w-10 h-10 rounded-lg bg-indigo-50 flex items-center justify-center text-indigo-600 font-bold text-lg shrink-0">
                        {project.name.charAt(0)}
                    </div>
                    <div className="min-w-0 pr-8">
                        <h3 className="font-semibold text-slate-800 truncate">{project.name}</h3>
                        <span className="text-xs text-slate-500 bg-slate-100 px-2 py-0.5 rounded-full inline-block truncate max-w-full">{project.industry}</span>
                    </div>
                </div>
                <p className="text-sm text-slate-500 line-clamp-3 mb-4 flex-1">{project.description}</p>
                <div className="flex items-center justify-between text-xs text-slate-400 pt-4 border-t border-slate-50 mt-auto">
                    <span>{new Date(project.createdAt).toLocaleDateString()}</span>
                    <span>{project.tone}</span>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

// --- Main App Component ---

function App() {
  const [user, setUser] = useState<User | null>(null);
  const [projects, setProjects] = useState<BrandProject[]>([]);
  const [view, setView] = useState<'dashboard' | 'new' | 'editor'>('dashboard');
  const [selectedProject, setSelectedProject] = useState<BrandProject | null>(null);
  
  // New Project State
  const [industry, setIndustry] = useState('');
  const [description, setDescription] = useState('');
  const [tone, setTone] = useState('Professional');
  const [language, setLanguage] = useState('English');
  const [isGenerating, setIsGenerating] = useState(false);
  const [isListening, setIsListening] = useState(false);

  // Load initial data
  useEffect(() => {
    const session = localStorage.getItem('bf_session');
    if (session) setUser(JSON.parse(session));
    
    const savedProjects = localStorage.getItem('bf_projects');
    if (savedProjects) setProjects(JSON.parse(savedProjects));
  }, []);

  // Save projects on change
  useEffect(() => {
    if (projects.length > 0) {
      localStorage.setItem('bf_projects', JSON.stringify(projects));
    }
  }, [projects]);

  const handleVoiceInput = () => {
    const SpeechRecognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
    if (!SpeechRecognition) {
      alert("Browser does not support speech recognition.");
      return;
    }
    const recognition = new SpeechRecognition();
    recognition.lang = 'en-US';
    recognition.start();
    setIsListening(true);
    recognition.onresult = (event: any) => {
      const transcript = event.results[0][0].transcript;
      setDescription(prev => prev + ' ' + transcript);
      setIsListening(false);
    };
    recognition.onerror = () => setIsListening(false);
    recognition.onend = () => setIsListening(false);
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
      if (e.target.files && e.target.files[0]) {
          alert(`File "${e.target.files[0].name}" attached. (Mock attachment)`);
          setDescription(prev => prev + ` [Attached: ${e.target.files![0].name}]`);
      }
  };

  const createProject = async () => {
    if (!industry || !description) return;
    setIsGenerating(true);
    try {
      const data = await generateBrandIdentity(industry, description, tone, language);
      const newProject: BrandProject = {
        id: Date.now().toString(),
        name: data.names[0].name, 
        industry,
        description,
        tone,
        language,
        generatedData: data,
        createdAt: Date.now()
      };
      setProjects([newProject, ...projects]);
      setSelectedProject(newProject);
      setView('editor');
    } catch (e) {
      alert("Failed to generate brand identity. Please check API Key and try again.");
    } finally {
      setIsGenerating(false);
    }
  };

  const updateProject = (updated: BrandProject) => {
    const updatedProjects = projects.map(p => p.id === updated.id ? updated : p);
    setProjects(updatedProjects);
    setSelectedProject(updated);
  };

  const deleteProject = (id: string) => {
      if(confirm("Are you sure you want to delete this project?")) {
        setProjects(projects.filter(p => p.id !== id));
      }
  };

  const renameProject = (id: string, name: string) => {
      setProjects(projects.map(p => p.id === id ? { ...p, name } : p));
  };

  // --- Render Logic ---

  if (!user) {
    return <AuthScreen onLogin={setUser} />;
  }

  if (view === 'editor' && selectedProject) {
    return (
      <ProjectEditor 
        project={selectedProject} 
        onUpdate={updateProject} 
        onBack={() => setView('dashboard')} 
      />
    );
  }

  if (view === 'new') {
    return (
      <div className="min-h-screen bg-slate-50 flex items-center justify-center p-4">
        <Card className="w-full max-w-2xl relative">
          <div className="flex justify-between items-center mb-6">
            <h2 className="text-2xl font-bold text-slate-800">New Brand Project</h2>
            <button onClick={() => setView('dashboard')} className="text-slate-400 hover:text-slate-600">
                <LogOut className="w-5 h-5 rotate-180" />
            </button>
          </div>
          
          <div className="space-y-6">
            <Input 
              label="Industry / Niche" 
              placeholder="e.g. Sustainable Fashion, SaaS, Coffee Shop" 
              value={industry}
              onChange={e => setIndustry(e.target.value)}
            />
            
            <div className="relative">
              <TextArea 
                label="Brand Description & Keywords" 
                placeholder="Describe your vision, target audience, and key values..."
                className="min-h-[120px] pb-10"
                value={description}
                onChange={e => setDescription(e.target.value)}
              />
              <div className="absolute bottom-3 left-3 flex gap-2">
                  <label className="p-2 rounded-full bg-slate-100 text-slate-500 hover:bg-slate-200 cursor-pointer transition-colors">
                      <Upload className="w-4 h-4" />
                      <input type="file" className="hidden" onChange={handleFileUpload} />
                  </label>
              </div>
              <button 
                onClick={handleVoiceInput}
                className={`absolute bottom-3 right-3 p-2 rounded-full transition-colors ${
                  isListening ? 'bg-red-100 text-red-600 animate-pulse' : 'bg-slate-100 text-slate-500 hover:bg-slate-200'
                }`}
              >
                {isListening ? <MicOff className="w-4 h-4" /> : <Mic className="w-4 h-4" />}
              </button>
            </div>

            <div className="grid grid-cols-2 gap-4">
               <Select 
                 label="Brand Tone" 
                 options={[
                   {value: 'Professional', label: 'Professional'},
                   {value: 'Playful', label: 'Playful'},
                   {value: 'Luxury', label: 'Luxury'},
                   {value: 'Minimalist', label: 'Minimalist'},
                   {value: 'Bold', label: 'Bold'},
                   {value: 'Friendly', label: 'Friendly'},
                   {value: 'Futuristic', label: 'Futuristic'},
                   {value: 'Earthy', label: 'Earthy'},
                 ]}
                 value={tone}
                 onChange={e => setTone(e.target.value)}
               />
               <Select 
                 label="Language" 
                 options={LANGUAGES}
                 value={language}
                 onChange={e => setLanguage(e.target.value)}
               />
            </div>

            <Button 
                onClick={createProject} 
                isLoading={isGenerating} 
                className="w-full py-4 text-lg shadow-xl shadow-indigo-200"
                disabled={!industry || !description}
            >
              <Sparkles className="w-5 h-5 mr-2" />
              Generate Brand Identity
            </Button>
          </div>
        </Card>
        <ChatWidget />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-50 relative">
       <nav className="bg-white/80 backdrop-blur-md border-b border-slate-200 sticky top-0 z-10">
           <div className="max-w-7xl mx-auto px-6 py-4 flex justify-between items-center">
               <div className="flex items-center gap-2">
                   <div className="w-8 h-8 bg-gradient-to-br from-indigo-500 to-purple-500 rounded-lg flex items-center justify-center">
                       <Sparkles className="w-5 h-5 text-white" />
                   </div>
                   <span className="font-bold text-xl text-slate-800">BrandForge AI</span>
               </div>
               <div className="flex items-center gap-4">
                   <span className="text-sm text-slate-500 hidden sm:inline">{user.name}</span>
                   <Button variant="ghost" onClick={() => { localStorage.removeItem('bf_session'); sessionStorage.removeItem('bf_chat_session'); setUser(null); }}>
                       <LogOut className="w-4 h-4" />
                   </Button>
               </div>
           </div>
       </nav>
       <Dashboard 
         user={user} 
         projects={projects} 
         onNew={() => setView('new')} 
         onSelect={(p) => { setSelectedProject(p); setView('editor'); }}
         onDelete={deleteProject}
         onRename={renameProject}
       />
       <ChatWidget />
    </div>
  );
}

export default App;